- name: installing python
  ansible.builtin.import_role:
   name: common
   tasks_from: python-setup
- name: checking user
  ansible.builtin.command: id roboshop
  register: out
  ignore_errors: true
- name: Add the user 'roboshop' after validating
  when: out.rc == 1
  ansible.builtin.user:
   name: roboshop  
- name: checking app directory
  ansible.builtin.stat:
   path: /app
  register: directory
- name: Create a directory app
  when: directory.stat.exists == False
  ansible.builtin.file:
   path: /app
   state: directory 
- name: Download "{{component}}".zip
  ansible.builtin.get_url:
   url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
   dest: /tmp 
          
- name: extract "{{component}}".zip
  ansible.builtin.unarchive:
   src: "/tmp/{{component}}.zip"
   dest: /app
   remote_src: yes   
- name: installing
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
   chdir: /app  

- name: copy "{{component}}" service
  ansible.builtin.copy:
   src: "{{component}}.service"
   dest: "/etc/systemd/system/{{component}}.service"   
- name: Reload "{{component}}"
  ansible.builtin.systemd:
   daemon_reload: true 
- name: restart {{component}}
  ansible.builtin.service:
    name: "{{component}}"
    enabled: yes
    state: restarted   
    
