- name: configuring yum repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
- name: configuring yum repos rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
- name: install rabbitmq
  ansible.builtin.yum:
   name: rabbitmq-server
   state: present    
- name: Start rabbitmq and enable
  ansible.builtin.service:
   name: rabbitmq-server 
   state: started
   enabled: true 
- name: creating user and setting permissions
  community.rabbitmq.rabbitmq_user:
   user: roboshop
   password: roboshop123
   vhost: /
   configure_priv: .*
   read_priv: .*
   write_priv: .*
   state: present
