- name: installing golang
  ansible.builtin.yum:
   name: golang
   state: present
- name: setting the app directory
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup
- name: download dependencies1
  ansible.builtin.command: go mod init dispatch
  args:
   chdir: /app   
- name: download dependencies2
  ansible.builtin.command: go get
  args:
   chdir: /app  
- name: download dependencies3
  ansible.builtin.command: go build
  args:
   chdir: /app        




- name: installing dependencies and systemd
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup          