- name: installing nodejs
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs
- name: setting the app directory
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup      