- name: checking user
  ansible.builtin.command: id roboshop
  register: out
  ignore_errors: true
- name: Add the user 'roboshop' after validating
  when: out.rc == 1
  ansible.builtin.user:
   name: roboshop  
- name: checking app directory
  ansible.builtin.stat:
   path: /app
   register: directory
- name: Create a directory app
  when: directory.stat.exists == False
  ansible.builtin.file:
   path: /app
   state: directory 
 - name: Download "{{component}}".zip
   ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/"{{component}}".zip
    dest: /tmp 
          
- name: extract "{{component}}".zip
  ansible.builtin.unarchive:
   src: /tmp/"{{component}}".zip
   dest: /app
   remote_src: yes   