- name: installing nodejs
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs
- name: setting the app directory
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup   
- name: download npm
  ansible.builtin.command: npm install 
  args:
   chdir: /app        

- name: installing dependencies and systemd
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup   
